import React, { useState } from 'react';
import { Image, ImageBackground, Platform, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Game } from './api';
import { s } from './styles';
import { Tap } from './Tap';

export type Site = { platformName: string; registrationEnabled: boolean; maintenanceMode: boolean; content: {
  brand: { logoGlyph: string; tagline: string; creditsLabel: string; demoBadge: string; legalNotice: string; footerNote: string };
  signIn: { formKicker: string; loginTitle: string; loginSubtitle: string; registerTitle: string; registerSubtitle: string; registrationClosed: string };
  lobby: { welcomeLabel: string; heroEnabled: boolean; featuredGameCode: string; heroEyebrow: string; heroHeadline: string; heroAccent: string; heroBody: string; heroNote: string; heroArtLabel: string; quickLinkTitle: string; quickLinkBody: string; libraryEyebrow: string; defaultBadge: string };
} };
const serif = Platform.OS === 'android' ? 'serif' : 'Georgia';
const classic = ['7','BAR','CHERRY','LEMON','BELL','GRAPE','ORANGE','WATERMELON','STAR'];
const fire = ['JADE_LION','RED_LANTERN','JADE_COMPASS','CRANE','KOI','FLAME_LOTUS'];
export function SymbolArt({ symbol, size = 80 }: { symbol: string; size?: number }) {
  const special = fire.includes(symbol), atlas = special ? fire : classic, index = atlas.indexOf(symbol);
  if (index < 0) return <Text style={{ color: '#efd49b', fontSize: size / 3, textAlign: 'center' }}>{symbol.replaceAll('_',' ')}</Text>;
  return <View accessibilityLabel={symbol} style={{ width: size, height: size, overflow: 'hidden' }}><Image source={special ? require('../assets/web/lucky-fire-blitz-symbols-v1.png') : require('../assets/web/slot-symbols.png')} style={{ position: 'absolute', width: size * 3, height: size * (special ? 2 : 3), left: -(index % 3) * size, top: -Math.floor(index / 3) * size }} /></View>;
}
export function Brand({ site }: { site: Site }) { return <View style={w.brand}><LinearGradient colors={['#fff0b4','#ad7c21']} style={w.logo}><Text style={w.logoText}>{site.content.brand.logoGlyph}</Text></LinearGradient><View style={w.brandLines}><Text numberOfLines={1} style={w.brandText}>{site.platformName.toUpperCase()}</Text><Text numberOfLines={1} style={w.tagline}>{site.content.brand.tagline}</Text></View></View>; }
export function AuthLook({ site, children }: { site: Site; children: React.ReactNode }) {
  const {width,height}=useWindowDimensions();
  if(width>height) return <View style={{flex:1,flexDirection:'row',backgroundColor:'#090706'}}><View style={{width:'43%',overflow:'hidden'}}><Image source={require('../assets/web/casino-host-login-v1.png')} style={{position:'absolute',width:height*1717/916,height,left:-height*.16}}/><LinearGradient colors={['#09070600','#090706bb']} style={{flex:1,padding:20,justifyContent:'space-between'}}><Brand site={site}/><Text style={[s.small,{color:'#e0cbaa'}]}>{site.content.brand.legalNotice}</Text></LinearGradient></View><ScrollView style={{flex:1}} contentContainerStyle={{padding:20,gap:14}} keyboardShouldPersistTaps="handled"><View style={[w.form,{marginTop:0,marginHorizontal:0,padding:20,gap:12}]}>{children}</View></ScrollView></View>;
  const pictureWidth=Math.max(width,680);
  return <ScrollView style={{backgroundColor:'#090706'}} contentContainerStyle={{paddingBottom:30}} keyboardShouldPersistTaps="handled"><View style={{height:362,overflow:'hidden'}}><Image source={require('../assets/web/casino-host-login-v1.png')} resizeMode="cover" style={{position:'absolute',width:pictureWidth,height:pictureWidth*916/1717,left:-(pictureWidth-width)*.28,top:0}}/><LinearGradient colors={['#09070600','#090706']} style={{flex:1,padding:24}}><Brand site={site}/></LinearGradient></View><View style={w.form}>{children}</View><Text style={[s.small,{textAlign:'center',padding:24}]}>{site.content.brand.legalNotice}</Text></ScrollView>;
}
const kind = (game: Game) => game.engine?.layout === 'ROULETTE' ? 'Table games' : game.engineType === 'CRASH' ? 'Arcade' : 'Slots';
export function WebLobby({site,games,onPlay}: {site:Site;games:Game[];onPlay:(g:Game)=>void}) {
  const {width,height}=useWindowDimensions();
  const landscape=width>height;
  const [search,setSearch]=useState(''), [category,setCategory]=useState('All games'), [favorites,setFavorites]=useState<string[]>([]);
  const copy=site.content.lobby, featured=games.find(g=>g.code===copy.featuredGameCode)||games[0];
  const cardWidth=Math.max(164,Math.min(240,Math.floor((width-132)/3)));
  const visible=games.filter(g=>g.name.toLowerCase().includes(search.toLowerCase())&&(category==='All games'||category===kind(g)||(category==='Favorites'&&favorites.includes(g.code))));
  const artSize=Math.max(54,Math.min(150,height-306));
  if(landscape) return <View style={{gap:10}}>
    <View style={w.spread}><View><Text style={w.eyebrow}>THE GAME ROOM</Text><Text style={[s.title,{fontFamily:serif,fontSize:22}]}>Find your favorite.</Text></View><TextInput accessibilityLabel="Search games" value={search} onChangeText={setSearch} placeholder="Search games" placeholderTextColor="#aaa0b9" style={[s.input,{width:Math.min(220,width*.25),minHeight:44,padding:10,fontSize:13}]}/></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{['All games','Arcade','Slots','Table games','Favorites'].map(c=><Tap key={c} haptic="select" accessibilityRole="tab" accessibilityState={{selected:c===category}} onPress={()=>setCategory(c)} style={[w.category,{minHeight:44,paddingVertical:12,paddingHorizontal:14,borderRadius:22},c===category&&{backgroundColor:'#efd49b',borderColor:'#efd49b'}]}><Text style={{color:c===category?'#271d11':'#c5bdcc',fontSize:12,fontWeight:'700'}}>{c}</Text></Tap>)}</ScrollView>
    <ScrollView key={category+search} horizontal showsHorizontalScrollIndicator={false} snapToInterval={cardWidth+12} decelerationRate="fast" contentContainerStyle={{gap:12,paddingVertical:2,paddingRight:12}}>
      {visible.map((game,index)=><LinearGradient key={game.code} colors={kind(game)==='Table games'?['#204344','#101e25']:game.theme==='FRUIT'?['#285a40','#112b25']:index%2?['#402d64','#1b142c']:['#602439','#240f1d']} style={{width:cardWidth,borderRadius:14,borderWidth:1,borderColor:'#ac884b88',overflow:'hidden'}}>
        <Tap haptic="heavy" accessibilityLabel={`Play ${game.name}`} onPress={()=>onPlay(game)} style={{alignItems:'center',padding:10}}>
          <View style={{width:'100%',height:18}}><Text style={[w.badge,{textAlign:'left',letterSpacing:1}]}>{kind(game).toUpperCase()}</Text></View>
          <View style={{height:artSize,alignItems:'center',justifyContent:'center',width:'100%'}}><View style={{position:'absolute',width:artSize,height:artSize,borderRadius:artSize,borderWidth:1,borderColor:'#f4d28b33',backgroundColor:'#f4d28b09'}}/><SymbolArt symbol={game.featuredSymbol||'7'} size={artSize}/></View>
          <Text numberOfLines={1} adjustsFontSizeToFit style={[w.posterTitle,{fontSize:20,height:27,marginVertical:4,width:'100%'}]}>{game.name}</Text>
          <View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',width:'100%',borderTopWidth:1,borderTopColor:'#ffffff15',paddingTop:4,minHeight:32}}><Text style={{color:'#ccbfca',fontSize:11}}>From {game.minStake.toFixed(2)}</Text><Text style={{color:'#efd49b',fontWeight:'800',fontSize:12}}>PLAY  ›</Text></View>
        </Tap>
        <Tap haptic="select" accessibilityLabel={`Favorite ${game.name}`} accessibilityState={{selected:favorites.includes(game.code)}} onPress={()=>setFavorites(previous=>previous.includes(game.code)?previous.filter(c=>c!==game.code):[...previous,game.code])} style={{position:'absolute',right:0,top:0,width:44,height:44,alignItems:'center',justifyContent:'center'}}><Text style={{color:'#efd49b',fontSize:22}}>{favorites.includes(game.code)?'♥':'♡'}</Text></Tap>
      </LinearGradient>)}
    </ScrollView>
    <View style={w.spread}><Text style={s.small}>{visible.length} games · Swipe to explore →</Text><Text style={s.small}>Demo credits · No cash value</Text></View>
    {!visible.length&&<Text style={s.muted}>No games in this selection. Try All games or another search.</Text>}
  </View>;
  return <>
    <View style={w.spread}><Text style={w.eyebrow}>{copy.welcomeLabel}</Text><Text style={w.eyebrow}>● {site.content.brand.demoBadge}</Text></View>
    {copy.heroEnabled&&featured&&category==='All games'&&!search&&<LinearGradient colors={['#21171b','#37131e','#140f16']} start={{x:0,y:0}} end={{x:1,y:1}} style={[w.hero,landscape&&{minHeight:190,padding:16}]}><View style={{flex:1.4,zIndex:1}}><Text style={w.eyebrow}>{copy.heroEyebrow}</Text><Text style={[w.headline,landscape&&{fontSize:25,lineHeight:27,marginVertical:8}]}>{copy.heroHeadline}{'\n'}<Text style={{color:'#d7b777',fontStyle:'italic'}}>{copy.heroAccent}</Text></Text><Text style={w.heroBody}>{copy.heroBody.replaceAll('{game}',featured.name)}</Text><Tap haptic="heavy" onPress={()=>onPlay(featured)}><LinearGradient colors={['#efd49b','#c9a366']} style={w.discover}><Text style={{fontSize:14,fontWeight:'700',color:'#271d11'}}>Discover {featured.name} ↗</Text></LinearGradient></Tap><Text style={[w.eyebrow,{marginTop:8}]}>{copy.heroNote}</Text></View><View style={w.heroArt}><View style={{position:'absolute',top:0,right:0}}><SymbolArt symbol="STAR" size={48}/></View><SymbolArt symbol={classic.includes(featured.featuredSymbol||'')?featured.featuredSymbol!:'STAR'} size={125}/><Text numberOfLines={1} style={w.artLabel}>{featured.name}</Text><Text numberOfLines={2} style={[w.eyebrow,{width:'100%',textAlign:'center'}]}>{copy.heroArtLabel}</Text></View></LinearGradient>}
    <View style={w.quick}><Text style={{color:'#bfa063',fontSize:24}}>✦</Text><View><Text style={{color:'#d0c6b5',fontSize:14,fontWeight:'600'}}>{copy.quickLinkTitle}</Text><Text style={s.small}>{copy.quickLinkBody}</Text></View></View>
    <View style={w.spread}><View><Text style={w.eyebrow}>{copy.libraryEyebrow}</Text><Text style={[s.title,{marginTop:6}]}>{category==='All games'?'All Games':category}</Text></View><Text style={s.small}>{visible.length} games</Text></View>
    <TextInput accessibilityLabel="Search games" value={search} onChangeText={setSearch} placeholder="⌕  Search games" placeholderTextColor="#96909e" style={s.input}/>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:7}}>{['All games','Arcade','Slots','Table games','Favorites'].map(c=><Tap key={c} haptic="select" accessibilityRole="tab" accessibilityState={{selected:c===category}} onPress={()=>setCategory(c)} style={[w.category,c===category&&{borderColor:'#bba16a55',backgroundColor:'#b29a561a'}]}><Text style={{color:c===category?'#efd49b':'#a9a5b0',fontSize:12}}>{c}</Text></Tap>)}</ScrollView>
    <View style={s.grid}>{visible.map(game=><View key={game.code} style={{width:landscape?'23%':'48%',flexGrow:0}}><LinearGradient colors={game.theme==='FRUIT'||game.theme==='CITRUS'?['#154b41','#256448','#0a232a']:kind(game)==='Table games'?['#271438','#4b235b','#151126']:['#33121d','#830c25','#190811']} style={w.poster}><Tap haptic="heavy" accessibilityLabel={`Play ${game.name}`} onPress={()=>onPlay(game)} style={[w.posterButton,landscape&&{minHeight:180,padding:8}]}><Text style={w.badge}>{game.presentation?.badge||copy.defaultBadge}</Text><View style={{marginTop:26,marginBottom:8}}><SymbolArt symbol={game.featuredSymbol||'7'} size={106}/></View><Text style={w.posterTitle}>{game.name}</Text><Text style={w.badge}>{game.presentation?.tileSubtitle}</Text></Tap><Tap haptic="select" accessibilityLabel={`Favorite ${game.name}`} accessibilityState={{selected:favorites.includes(game.code)}} onPress={()=>setFavorites(previous=>previous.includes(game.code)?previous.filter(c=>c!==game.code):[...previous,game.code])} style={w.heart}><Text style={{color:'#fff',fontSize:24}}>{favorites.includes(game.code)?'♥':'♡'}</Text></Tap></LinearGradient><Text style={w.caption}>{game.name}</Text><Text style={s.small}>{kind(game)} · From {game.minStake.toFixed(2)} credits</Text></View>)}</View>
    {!visible.length&&<Text style={s.muted}>{category==='Favorites'?'Tap the heart on a game to save it for this visit.':'No games found. Try another search.'}</Text>}
    <Text style={[s.small,{marginTop:16}]}>{site.content.brand.footerNote}</Text>
  </>;
}
const w=StyleSheet.create({
  brand:{flexDirection:'row',alignItems:'center',gap:8,flexShrink:1,minWidth:0},brandLines:{flexShrink:1,minWidth:0},logo:{width:33,height:37,borderRadius:9,alignItems:'center',justifyContent:'center'},logoText:{color:'#201707',fontSize:25,fontWeight:'800'},brandText:{color:'#f3e9d3',fontSize:12,letterSpacing:1.5,fontWeight:'700'},tagline:{fontSize:11,letterSpacing:.8,color:'#b7a78d',marginTop:3},form:{marginHorizontal:24,marginTop:-42,padding:24,gap:18,borderWidth:1,borderColor:'#bb914a44',borderRadius:8,backgroundColor:'#14110e'},
  spread:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8},eyebrow:{color:'#ae9364',fontSize:11,letterSpacing:1.1},hero:{borderWidth:1,borderColor:'#bd925342',borderRadius:16,minHeight:250,padding:20,flexDirection:'row',overflow:'hidden'},headline:{fontFamily:serif,color:'#fff2db',fontSize:29,letterSpacing:-1,lineHeight:31,marginVertical:12},heroBody:{color:'#b8a8a4',fontSize:13,lineHeight:19},discover:{borderRadius:7,padding:12,marginTop:14},heroArt:{flex:1,minWidth:0,alignItems:'center',justifyContent:'center',paddingTop:20},artLabel:{fontFamily:serif,fontStyle:'italic',fontSize:18,color:'#ebcf8a',textAlign:'center',width:'100%'},quick:{flexDirection:'row',gap:12,alignItems:'center',paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#ffffff12'},category:{borderWidth:1,borderColor:'#ffffff10',borderRadius:24,backgroundColor:'#14141b',paddingHorizontal:15,paddingVertical:13},poster:{borderRadius:14,overflow:'hidden',borderWidth:1,borderColor:'#ffffff22'},posterButton:{minHeight:224,alignItems:'center',justifyContent:'flex-end',padding:12},badge:{fontSize:11,letterSpacing:.8,color:'#e6c9a1',textAlign:'center'},posterTitle:{fontFamily:serif,fontWeight:'900',fontStyle:'italic',fontSize:23,color:'#ffdf9d',textAlign:'center',marginBottom:8},heart:{position:'absolute',left:9,top:9,width:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:20,borderWidth:1,borderColor:'#ffffff35',backgroundColor:'#ffffff24'},caption:{fontSize:12,fontWeight:'600',color:'#eee4d5',marginTop:10,marginBottom:4},
});
