import React, { useState } from 'react';
import { Image, ImageBackground, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Game } from './api';
import { s } from './styles';

export type Site = { platformName: string; registrationEnabled: boolean; maintenanceMode: boolean; content: {
  brand: { logoGlyph: string; tagline: string; creditsLabel: string; demoBadge: string; legalNotice: string; footerNote: string };
  signIn: { formKicker: string; loginTitle: string; loginSubtitle: string; registerTitle: string; registerSubtitle: string; registrationClosed: string };
  lobby: { welcomeLabel: string; heroEnabled: boolean; featuredGameCode: string; heroEyebrow: string; heroHeadline: string; heroAccent: string; heroBody: string; heroNote: string; heroArtLabel: string; quickLinkTitle: string; quickLinkBody: string; libraryEyebrow: string; defaultBadge: string };
} };
const serif = Platform.OS === 'android' ? 'serif' : 'Georgia';
const classic = ['7','BAR','CHERRY','LEMON','BELL','GRAPE','ORANGE','WATERMELON','STAR'];
const fire = ['JADE_LION','RED_LANTERN','JADE_COMPASS','CRANE','KOI','FLAME_LOTUS'];
export function SymbolArt({ symbol, size = 80 }: { symbol: string; size?: number }) {
  const special = fire.includes(symbol), atlas = special ? fire : classic, index = atlas.indexOf(symbol);
  if (index < 0) return <Text style={{ color: '#efd49b', fontSize: size / 3, textAlign: 'center' }}>{symbol.replaceAll('_',' ')}</Text>;
  return <View accessibilityLabel={symbol} style={{ width: size, height: size, overflow: 'hidden' }}><Image source={special ? require('../assets/web/lucky-fire-blitz-symbols-v1.png') : require('../assets/web/slot-symbols.png')} style={{ position: 'absolute', width: size * 3, height: size * (special ? 2 : 3), left: -(index % 3) * size, top: -Math.floor(index / 3) * size }} /></View>;
}
export function Brand({ site }: { site: Site }) { return <View style={w.brand}><LinearGradient colors={['#fff0b4','#ad7c21']} style={w.logo}><Text style={w.logoText}>{site.content.brand.logoGlyph}</Text></LinearGradient><View><Text style={w.brandText}>{site.platformName.toUpperCase()}</Text><Text style={w.tagline}>{site.content.brand.tagline}</Text></View></View>; }
export function AuthLook({ site, children }: { site: Site; children: React.ReactNode }) {
  const {width}=useWindowDimensions();
  const pictureWidth=Math.max(width,680);
  return <ScrollView style={{backgroundColor:'#090706'}} contentContainerStyle={{paddingBottom:30}} keyboardShouldPersistTaps="handled"><View style={{height:362,overflow:'hidden'}}><Image source={require('../assets/web/casino-host-login-v1.png')} resizeMode="cover" style={{position:'absolute',width:pictureWidth,height:pictureWidth*916/1717,left:-(pictureWidth-width)*.28,top:0}}/><LinearGradient colors={['#09070600','#090706']} style={{flex:1,padding:24}}><Brand site={site}/></LinearGradient></View><View style={w.form}>{children}</View><Text style={[s.small,{textAlign:'center',padding:24,fontSize:8}]}>{site.content.brand.legalNotice}</Text></ScrollView>;
}
const kind = (game: Game) => game.engine?.layout === 'ROULETTE' ? 'Table games' : game.engineType === 'CRASH' ? 'Arcade' : 'Slots';
export function WebLobby({site,games,onPlay}: {site:Site;games:Game[];onPlay:(g:Game)=>void}) {
  const [search,setSearch]=useState(''), [category,setCategory]=useState('All games'), [favorites,setFavorites]=useState<string[]>([]);
  const copy=site.content.lobby, featured=games.find(g=>g.code===copy.featuredGameCode)||games[0];
  const visible=games.filter(g=>g.name.toLowerCase().includes(search.toLowerCase())&&(category==='All games'||category===kind(g)||(category==='Favorites'&&favorites.includes(g.code))));
  return <>
    <View style={w.spread}><Text style={w.eyebrow}>{copy.welcomeLabel}</Text><Text style={w.eyebrow}>● {site.content.brand.demoBadge}</Text></View>
    {copy.heroEnabled&&featured&&category==='All games'&&!search&&<LinearGradient colors={['#21171b','#37131e','#140f16']} start={{x:0,y:0}} end={{x:1,y:1}} style={w.hero}><View style={{flex:1.4,zIndex:1}}><Text style={w.eyebrow}>{copy.heroEyebrow}</Text><Text style={w.headline}>{copy.heroHeadline}{'\n'}<Text style={{color:'#d7b777',fontStyle:'italic'}}>{copy.heroAccent}</Text></Text><Text style={w.heroBody}>{copy.heroBody.replaceAll('{game}',featured.name)}</Text><Pressable accessibilityRole="button" onPress={()=>onPlay(featured)}><LinearGradient colors={['#f4dfab','#c9a366']} style={w.discover}><Text style={{fontSize:10,fontWeight:'700',color:'#271d11'}}>Discover {featured.name} ↗</Text></LinearGradient></Pressable><Text style={[w.eyebrow,{fontSize:6,marginTop:8}]}>{copy.heroNote}</Text></View><View style={w.heroArt}><View style={{position:'absolute',top:0,right:0}}><SymbolArt symbol="STAR" size={48}/></View><SymbolArt symbol={classic.includes(featured.featuredSymbol||'')?featured.featuredSymbol!:'STAR'} size={125}/><Text style={w.artLabel}>{featured.name}</Text><Text style={[w.eyebrow,{fontSize:5}]}>{copy.heroArtLabel}</Text></View></LinearGradient>}
    <View style={w.quick}><Text style={{color:'#bfa063',fontSize:24}}>✦</Text><View><Text style={{color:'#d0c6b5',fontSize:12}}>{copy.quickLinkTitle}</Text><Text style={[s.small,{fontSize:9}]}>{copy.quickLinkBody}</Text></View></View>
    <View style={w.spread}><View><Text style={w.eyebrow}>{copy.libraryEyebrow}</Text><Text style={[s.title,{marginTop:6}]}>{category==='All games'?'All Games':category}</Text></View><Text style={s.small}>{visible.length} games</Text></View>
    <TextInput accessibilityLabel="Search games" value={search} onChangeText={setSearch} placeholder="⌕  Search games" placeholderTextColor="#96909e" style={s.input}/>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:7}}>{['All games','Arcade','Slots','Table games','Favorites'].map(c=><Pressable key={c} accessibilityRole="button" accessibilityState={{selected:c===category}} onPress={()=>setCategory(c)} style={[w.category,c===category&&{borderColor:'#b29a5655',backgroundColor:'#b29a561a'}]}><Text style={{color:c===category?'#f3dda0':'#a9a5b0',fontSize:12}}>{c}</Text></Pressable>)}</ScrollView>
    <View style={s.grid}>{visible.map(game=><View key={game.code} style={{width:'48%',flexGrow:1}}><LinearGradient colors={game.theme==='FRUIT'||game.theme==='CITRUS'?['#154b41','#256448','#0a232a']:kind(game)==='Table games'?['#271438','#4b235b','#151126']:['#33121d','#830c25','#190811']} style={w.poster}><Pressable accessibilityRole="button" accessibilityLabel={`Play ${game.name}`} onPress={()=>onPlay(game)} style={w.posterButton}><Text style={w.badge}>{game.presentation?.badge||copy.defaultBadge}</Text><View style={{marginTop:26,marginBottom:8}}><SymbolArt symbol={game.featuredSymbol||'7'} size={106}/></View><Text style={w.posterTitle}>{game.name}</Text><Text style={w.badge}>{game.presentation?.tileSubtitle}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Favorite ${game.name}`} accessibilityState={{selected:favorites.includes(game.code)}} onPress={()=>setFavorites(previous=>previous.includes(game.code)?previous.filter(c=>c!==game.code):[...previous,game.code])} style={w.heart}><Text style={{color:'#fff',fontSize:24}}>{favorites.includes(game.code)?'♥':'♡'}</Text></Pressable></LinearGradient><Text style={w.caption}>{game.name}</Text><Text style={[s.small,{fontSize:9}]}>{kind(game)} · From {game.minStake.toFixed(2)} credits</Text></View>)}</View>
    {!visible.length&&<Text style={s.muted}>{category==='Favorites'?'Tap the heart on a game to save it for this visit.':'No games found. Try another search.'}</Text>}
    <Text style={[s.small,{marginTop:16}]}>{site.content.brand.footerNote}</Text>
  </>;
}
const w=StyleSheet.create({
  brand:{flexDirection:'row',alignItems:'center',gap:8},logo:{width:33,height:37,borderRadius:9,alignItems:'center',justifyContent:'center'},logoText:{color:'#201707',fontSize:25,fontWeight:'800'},brandText:{color:'#f3e9d3',fontSize:10,letterSpacing:1.5,fontWeight:'700'},tagline:{fontSize:5,letterSpacing:1,color:'#b7a78d',marginTop:5},form:{marginHorizontal:24,marginTop:-42,padding:24,gap:18,borderWidth:1,borderColor:'#bb914a44',borderRadius:8,backgroundColor:'#14110e'},
  spread:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8},eyebrow:{color:'#ae9364',fontSize:7,letterSpacing:1.3},hero:{borderWidth:1,borderColor:'#bd925342',borderRadius:16,minHeight:250,padding:20,flexDirection:'row',overflow:'hidden'},headline:{fontFamily:serif,color:'#fff2db',fontSize:29,letterSpacing:-1,lineHeight:31,marginVertical:12},heroBody:{color:'#b8a8a4',fontSize:10,lineHeight:16},discover:{borderRadius:7,padding:12,marginTop:14},heroArt:{flex:1,alignItems:'center',justifyContent:'center',paddingTop:20},artLabel:{fontFamily:serif,fontStyle:'italic',fontSize:18,color:'#ebcf8a',textAlign:'center'},quick:{flexDirection:'row',gap:12,alignItems:'center',paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#ffffff12'},category:{borderWidth:1,borderColor:'#ffffff10',borderRadius:24,backgroundColor:'#14141b',paddingHorizontal:15,paddingVertical:13},poster:{borderRadius:14,overflow:'hidden',borderWidth:1,borderColor:'#ffffff22'},posterButton:{minHeight:224,alignItems:'center',justifyContent:'flex-end',padding:12},badge:{fontSize:6,letterSpacing:1,color:'#e6c9a1',textAlign:'center'},posterTitle:{fontFamily:serif,fontWeight:'900',fontStyle:'italic',fontSize:23,color:'#ffdf9d',textAlign:'center',marginBottom:8},heart:{position:'absolute',left:9,top:9,width:38,height:38,alignItems:'center',justifyContent:'center',borderRadius:20,borderWidth:1,borderColor:'#ffffff35',backgroundColor:'#ffffff24'},caption:{fontSize:12,fontWeight:'600',color:'#eee4d5',marginTop:10,marginBottom:4},
});
